version: '3.8'

services:
  fastapi:
    build: .
    container_name: fastapi-app
    ports:
      - ${APP_PORT}:${APP_PORT} 
    env_file: ./.env
    depends_on:
      - mysql-db 

  mysql-db:
    image: mysql:8.0
    restart: always
    container_name: talentod-db
    env_file: ./.env
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - mysql-volume:/var/lib/mysql

volumes:
  mysql-volume:
    external: true
